name: Go

on: push

jobs:

  unit-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Test
      run: make test

  step2:
    runs-on: macos-latest
    needs: unit-test

    steps:
    - name: Print if success, then trigger failure
      run: |
        echo "Completed job 2, but triggering failure"
        exit 1

  never:
    runs-on: macos-latest
    needs: step2

    steps:
    - name: Will never run
      run: |
        echo "If you can read this, the experiment failed"


